name: py
    
on:
 repository_dispatch:
 workflow_dispatch:
 schedule:
   - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: first

    steps:
      - name: Cancel Previous Workflow Runs
        uses: n1hility/cancel-previous-runs@v2.0
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python app.py

        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
